# This file was generated by GoReleaser. DO NOT EDIT.
cask "midtown" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "5a783c60224b7fea422719bf59eb2a6d33915557473e0ad2cc98b94e3ef939f2"
      url "https://github.com/bleupen/midtown/releases/download/v#{version}/midtown_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "192ec33d757c5e22ec00b2ee643168759bcde22531b267059d2495303b854d78"
      url "https://github.com/bleupen/midtown/releases/download/v#{version}/midtown_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "473f457a998dff5abc99308180fcb30c85a920e2a17d04f615666f6d4e3421ce"
      url "https://github.com/bleupen/midtown/releases/download/v#{version}/midtown_#{version}_linux_arm64.tar.gz"
    end
  end

  name "midtown"
  desc "Self-hosted HTTP tunnel client"
  homepage "https://github.com/bleupen/midtown"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "midtown"

  # No zap stanza required

end
