# This file was generated by GoReleaser. DO NOT EDIT.
cask "midtown" do
  version "0.1.4"

  on_macos do
    on_arm do
      sha256 "b796d644ec38a6883c1e1074bc61e192a8605f0b159ed6c0df2255a0f6052f87"
      url "https://github.com/bleupen/midtown-dist/releases/download/v#{version}/midtown_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b263ae58d5982ee829b6ab145ece155e40bdb2ecddb91d3721944ed60bdf1c69"
      url "https://github.com/bleupen/midtown-dist/releases/download/v#{version}/midtown_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0ae0aa6e16822b7556e1edbf90309b1ad87d559fc9341350dbe5c32985fe9814"
      url "https://github.com/bleupen/midtown-dist/releases/download/v#{version}/midtown_#{version}_linux_arm64.tar.gz"
    end
  end

  name "midtown"
  desc "Self-hosted HTTP tunnel client"
  homepage "https://github.com/bleupen/midtown-dist"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "midtown"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/midtown"]
    end
  end

  # No zap stanza required

end
